### ISSUE TITLE
Notion cannot display the graph chain of TMDB

### ISSUE THREAD

**Issue by likemuuxi** [Royal-lobster/watchlister-nextjs#3]
Do the author know the reason or solution？

**Comment by Royal-lobster** [comment]
Graph chain ?

**Comment by likemuuxi** [comment]
> Graph chain ?

Sorry for the incorrect expression, as shown in the picture below, the image does not display

![image](https://github.com/Royal-lobster/Watchlister/assets/85612715/bca3c68a-4892-4609-b479-776ecba65f59)

**Comment by likemuuxi** [comment]
> > Graph chain ?
> 
> Sorry for the incorrect expression, as shown in the picture below, the image does not display
> 
> ![image](https://private-user-images.githubusercontent.com/85612715/295166715-bca3c68a-4892-4609-b479-776ecba65f59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTQyMjIsIm5iZiI6MTcwNDc5MzkyMiwicGF0aCI6Ii84NTYxMjcxNS8yOTUxNjY3MTUtYmNhM2M2OGEtNDg5Mi00NjA5LWI0NzktNzc2ZWNiYTY1ZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA5NTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZGMwOGJhYzQ3ODFhYjYzZDUxNmE0NTdlMGUzYzNhMzkyNzJmZDliMWM1MDIwOTg0ZDU1M2ZhODE0ZmY2ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.azvDI0vax6-ArUSDAJt1kQWE4Bl2jAVR3ldfj1FgGzc)

Previously, it could have been displayed normally, could it be due to the network environment in China? I have already enabled VPN.

**Comment by Royal-lobster** [comment]
Ohh wierd, its not working for me as well, seems like notion changed something with their images

**Comment by likemuuxi** [comment]
I also think so, but I tried to copy the link of the image to the notion, which can be displayed.

**Comment by GbDavid00** [comment]
Hello. I have the same problem, do u have a correction date preview? 
Thanks for you work on this. <3
